# Generated by Django 5.2 on 2025-04-06 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Project Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='project_images/', verbose_name='Project Image')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Project Link')),
                ('technologies', models.CharField(blank=True, help_text='Comma-separated list of technologies (e.g., Python, Django, JavaScript)', max_length=200, verbose_name='Technologies Used')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Section Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('order', models.IntegerField(default=0, help_text='Used to determine the order of appearance (lower numbers appear first).', verbose_name='Order')),
                ('animation_style', models.CharField(blank=True, choices=[('', 'None'), ('fade-in', 'Fade In'), ('slide-in-left', 'Slide In Left'), ('slide-in-right', 'Slide In Right')], default='', help_text='Select a CSS class to apply an animation to this section.', max_length=50, verbose_name='Animation Style (CSS Class)')),
                ('is_active', models.BooleanField(default=True, help_text='Only active sections will be displayed on the site.', verbose_name='Active?')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Video Title')),
                ('video_file', models.FileField(upload_to='videos/', verbose_name='Video File')),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional image to display before the video plays.', null=True, upload_to='video_thumbnails/', verbose_name='Thumbnail (Optional)')),
                ('description', models.TextField(blank=True, verbose_name='Description (Optional)')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profile Picture')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Job Title')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn Profile URL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub Profile URL')),
                ('website_url', models.URLField(blank=True, verbose_name='Personal Website URL')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
