# Generated by Django 5.2 on 2025-04-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Episode Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cover_image', models.ImageField(upload_to='podcast_covers/', verbose_name='Cover Image')),
                ('audio_file', models.FileField(upload_to='podcast_audio/', verbose_name='Audio File (MP3, etc.)')),
                ('duration', models.CharField(blank=True, max_length=20, verbose_name='Duration (e.g., 30:15)')),
                ('publication_date', models.DateField(verbose_name='Publication Date')),
                ('order', models.IntegerField(default=0, verbose_name='Order (Recent first usually)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
            ],
            options={
                'verbose_name': 'Podcast Episode',
                'verbose_name_plural': 'Podcast Episodes',
                'ordering': ['-publication_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Project Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('video_file', models.FileField(upload_to='project_videos/', verbose_name='Video File')),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='project_posters/', verbose_name='Video Poster Image (Optional)')),
                ('technologies', models.CharField(blank=True, help_text='Comma-separated (e.g., HTML, CSS, Python)', max_length=200, verbose_name='Technologies Used')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Project Link (Optional)')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
            ],
            options={
                'verbose_name': 'Video Project',
                'verbose_name_plural': 'Video Projects',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order'], 'verbose_name': 'Managed Section', 'verbose_name_plural': 'Managed Sections'},
        ),
        migrations.AddField(
            model_name='section',
            name='identifier',
            field=models.CharField(blank=True, help_text="Unique ID for this section (e.g., 'about', 'contact_info'). Used internally.", max_length=50, null=True, unique=True, verbose_name='Identifier'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='section',
            name='animation_style',
            field=models.CharField(blank=True, choices=[('', 'None'), ('fade-up', 'Fade Up'), ('fade-down', 'Fade Down'), ('fade-left', 'Fade Left'), ('fade-right', 'Fade Right'), ('zoom-in', 'Zoom In')], default='fade-up', max_length=50, verbose_name='AOS Animation Style'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(blank=True, verbose_name='Content (HTML allowed if needed)'),
        ),
        migrations.AlterField(
            model_name='section',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active?'),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Section Title (Optional)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job_title',
            field=models.CharField(blank=True, help_text='e.g., Web Developer | Graphic Designer', max_length=100, verbose_name='Job Title(s)'),
        ),
    ]
