# Generated by Django 5.2 on 2025-04-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_certificate_experience_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المشروع')),
                ('description', models.TextField(verbose_name='وصف المشروع')),
                ('technologies', models.CharField(blank=True, max_length=500, null=True, verbose_name='التقنيات المستخدمة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='صورة المشروع')),
                ('link', models.URLField(blank=True, null=True, verbose_name='رابط المشروع')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'مشاريعي',
                'ordering': ['order'],
            },
        ),
    ]
